package com.sdcode.cryptotracker.apimanager.singlecoinhistoricalinfo;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.Date;

public class AtlDate{
    public Date aed;
    public Date ars;
    public Date aud;
    public Date bch;
    public Date bdt;
    public Date bhd;
    public Date bmd;
    public Date bnb;
    public Date brl;
    public Date btc;
    public Date cad;
    public Date chf;
    public Date clp;
    public Date cny;
    public Date czk;
    public Date dkk;
    public Date dot;
    public Date eos;
    public Date eth;
    public Date eur;
    public Date gbp;
    public Date hkd;
    public Date huf;
    public Date idr;
    public Date ils;
    public Date inr;
    public Date jpy;
    public Date krw;
    public Date kwd;
    public Date lkr;
    public Date ltc;
    public Date mmk;
    public Date mxn;
    public Date myr;
    public Date ngn;
    public Date nok;
    public Date nzd;
    public Date php;
    public Date pkr;
    public Date pln;
    public Date rub;
    public Date sar;
    public Date sek;
    public Date sgd;
    public Date thb;
    @JsonProperty("try") 
    public Date mytry;
    public Date twd;
    public Date uah;
    public Date usd;
    public Date vef;
    public Date vnd;
    public Date xag;
    public Date xau;
    public Date xdr;
    public Date xlm;
    public Date xrp;
    public Date yfi;
    public Date zar;
    public Date bits;
    public Date link;
    public Date sats;
}
